version: "3.7"
services:
  server:
    container_name: server
    build:
      context: ./server
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
    volumes:
      - ./server:/server/
      - /server/node_modules
  client:
    container_name: client
    build:
      context: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/client/
      - /client/node_modules
